name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Annotate ESLint failures
        if: steps.eslint.outcome == 'failure'
        run: |
          echo "::error title=ESLint violations detected::Run 'npm run lint:fix' locally to auto-fix where possible, then commit the changes."
          echo "ESLint reported issues. See logs above for file/line details." >> "$GITHUB_STEP_SUMMARY"
          exit 1

      - name: Run Prettier check
        id: prettier
        run: npm run format:check
        continue-on-error: true

      - name: Annotate Prettier failures
        if: steps.prettier.outcome == 'failure'
        run: |
          echo "::error title=Prettier formatting issues::Run 'npm run format' locally to write fixes, then commit the changes."
          echo "Prettier reported formatting issues." >> "$GITHUB_STEP_SUMMARY"
          exit 1

      - name: Success Summary
        if: ${{ success() }}
        run: |
          echo "✅ ESLint and Prettier checks passed." >> "$GITHUB_STEP_SUMMARY"
